export const COM_STATUS = 'COM_STATUS'
export const COM_SET_DESK_ID = 'COM_SET_DESK_ID'
export const COM_STORE_DESK_INFO = 'COM_STORE_DESK_INFO'
export const COM_CLEAR_DESK = 'COM_CLEAR_DESK'
export const COM_SET_FIRST_LOADING = 'COM_SET_FIRST_LOADING'
// HEADER
export const HEADER_SET_SHOWBACK = 'HEADER_SET_SHOWBACK'
export const HEADER_SET_SHOWCENTER = 'HEADER_SET_SHOWCENTER'
export const HEADER_SET_GOTO_CENTER = 'HEADER_SET_GOTO_CENTER'
// BOTTOM
export const BOTTOM_SHOW_BOTTOM = 'BOTTOM_SHOW_BOTTOM'
export const BOTTOM_SET_BOTTOM_TYPE = 'BOTTOM_SET_BOTTOM_TYPE'
// HOME
export const HOME_SET_TITLE = 'HOME_SET_TITLE'
export const HOME_SET_CONTENT = 'HOME_SET_CONTENT'

// bottom
export const BOTTOM_ADD_FOODS_BASKET = 'BOTTOM_ADD_FOODS_BASKET'
export const BOTTOM_CLEAR_FOODS_BASKET = 'BOTTOM_CLEAR_FOODS_BASKET'
export const BOTTOM_CHANGE_FOODS_BASKET = 'BOTTOM_CHANGE_FOODS_BASKET'
export const BOTTOM_SET_ISCHANGE_BASKET = 'BOTTOM_SET_ISCHANGE_BASKET'
export const BOTTOM_CLEAR_DELETE_BASKET = 'BOTTOM_CLEAR_DELETE_BASKET'
export const BOTTOM_UPDATE_FOODS_BASKET = 'BOTTOM_UPDATE_FOODS_BASKET'
export const BOTTOM_UPDATE_ORDER_NOTES = 'BOTTOM_UPDATE_ORDER_NOTES'
export const BOTTOM_SET_FOODS_BASKET = 'BOTTOM_SET_FOODS_BASKET'
export const BOTTOM_UPDATE_INIT_BASKET = 'BOTTOM_UPDATE_INIT_BASKET'
// ws
export const WS_STORE_CLIENT_ID = 'WS_STORE_CLIENT_ID'
export const WS_CLEAR_CLIENT_ID = 'WS_CLEAR_CLIENT_ID'

// user
export const USER_SET_ORDER_LIST = 'USER_SET_ORDER_LIST'
